AWSTemplateFormatVersion: '2010-09-09'
Description: Testing GitHub Actions

Resources:

  rParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: MyParameter
      Type: String
      Value: Hi! 2
      Description: Testing GitHub Actions - Delete this.
  
  rParameter2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: MyParameter2
      Type: String
      Value: Hi! 2
      Description: Testing GitHub Actions - Delete this.
  
  rSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecretTEst
      Description: "Testing GitHub Actions - Delete this."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'