AWSTemplateFormatVersion: '2010-09-09'
Description: Testing GitHub Actions

Parameters:
  pEnv:
    Type: String
    Default: dev
  pParameterName1:
    Type: String
    Default: p1
  pParameterName2:
    Type: String
    Default: p1


Resources:
  rParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['-', [Ref: pParameterName1, Ref: pEnv]]
      Type: String
      Value: Hi! 2
      Description: Testing GitHub Actions - Delete this.
  
  rParameter2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: MyParameter2
      Type: String
      Value: Hi! 2
      Description: Testing GitHub Actions - Delete this.
  
  rSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecretTEst
      Description: "Testing GitHub Actions - Delete this."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'