AWSTemplateFormatVersion: '2010-09-09'
Description: Testing GitHub Actions

Resources:

  rParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: MyParameter
      Type: String
      Value: Hi! 2
      Description: Testing GitHub Actions - Delete it.
  
  rParameter2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: MyParameter
      Type: String
      Value: Hi! 2
      Description: Testing GitHub Actions - Delete it.