name: Cloudformation Deployment - Reusable workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: script
        run: |
            echo Hi :D!