name: Cloudformation Deployment - Reusable workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      region:
        type: string
        required: false
        default: 'us-east-1'
    secrets:
      access-key-id:
        required: true
      secret-access-key:
        required: true


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: script
        run: |
          cat $GITHUB_EVENT_PATH

      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access-key-id }}
          aws-secret-access-key: ${{ secrets.secret-access-key }}
          aws-region: ${{ inputs.region }}

      - name: script
        run: |
          echo Hi :D!

# https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions