name: Cloudformation Deployment - Reusable workflow

on: 
  workflow_call:
    inputs:
      region:
        type: string
        required: false
        default: us-east-1
        description: AWS Region
      template:
        type: string
        required: true
        description: Path of the Cloudformation Template .yaml


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.region }}

      - name: script
        run: |
          echo Hi :D!

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT=`echo $REPO | tr "/" "-"`
          echo "Environment name: $ENVIRONMENT"
          echo "::set-output name=environment::$ENVIRONMENT"

      - name: Run Checkov analysis
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          file: ${{ inputs.template }}
          framework: cloudformation

      - name: Deploy Cloudformation Template
        id: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ steps.env-name.outputs.environment }}-cluster
          template: ${{ inputs.template }}


# https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions