name: Cloudformation Deployment - Reusable workflow

on: 
  workflow_call:
    inputs:
      region:
        type: string
        required: false
        default: us-east-1
        description: AWS Region
      cf_template:
        type: string
        required: true
        description: Path of the Cloudformation Template .yaml
      parameters_file:
        type: string
        required: true
        description: Path of the parameters file.

jobs:
  build:
    name: Deploy Cloudformation Template
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.region }}

      - name: Script
        run: |
          echo Deploying Cloudformation Template

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT=`echo $REPO | tr "/" "-"`
          echo "Environment name: $ENVIRONMENT"
          echo "::set-output name=environment::$ENVIRONMENT"

      # https://github.com/bridgecrewio/checkov-action
      - name: Run Checkov analysis
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          file: ${{ inputs.cf_template }}
          framework: cloudformation
          soft_fail: true

    
      
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: ${{ inputs.parameters_file }}
      
      - name: File contents
        run: echo ${ steps.read_file.outputs.contents }



      # https://github.com/aws-actions/aws-cloudformation-github-deploy
      #- name: Deploy Cloudformation Template
      #  id: deploy
      #  uses: aws-actions/aws-cloudformation-github-deploy@v1
      #  with:
      #    name: ${{ steps.env-name.outputs.environment }}-cluster
      #    template: ${{ inputs.cf_template }}
      #    no-fail-on-empty-changeset: "1"
      #    parameter-overrides:

