name: Cloudformation Deployment - Reusable workflow

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: false
        default: us-east-1
        description: region
    #secrets:
      access-key-id:
        type: string
        required: true
        description: access-key-id
      secret-access-key:
        type: string
        required: true
        description: secret-access-key
    
  workflow_call:
    


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.access-key-id }}
          aws-secret-access-key: ${{ inputs.secret-access-key }}
          aws-region: ${{ inputs.region }}

      - name: script
        run: |
          echo Hi :D!

# https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions