name: CD Cloudformation

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    #with:
    #  config-path: .github/labeler.yml