name: CD Cloudformation

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: false
        default: us-east-1
        description: AWS Region

jobs:
  deploy-dev:
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    with:
      template: ./template.yaml
    secrets: inherit # pass all secrets
  
  deploy-qa:
    needs: deploy-dev
    permissions:
      id-token: write
      contents: read
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    with:
      template: ./template.yaml
    secrets: inherit # pass all secrets