name: CD Cloudformation

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: false
        default: us-east-1
        description: AWS Region

jobs:
  call-workflow-passing-data:
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    with:
      region: ${{ github.event.inputs.region }}