name: CD Cloudformation

on:
  workflow_dispatch:
    inputs:
      cf_template:
        type: string
        required: false
        default: ./template.yaml
        description: Path of the Cloudformation Template .yaml

jobs:
  deploy-dev:
    name: Deploy DEV
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    secrets: inherit # pass all secrets
    with:
      cf_template: ${{ github.event.inputs.cf_template }}
      parameters_file: ./parameters-dev
      stack_name: test-github-actions-dev

  deploy-qa:
    name: Deploy QA
    needs: deploy-dev
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    secrets: inherit # pass all secrets
    with:
      cf_template: ${{ github.event.inputs.cf_template }}
      parameters_file: ./parameters-dev
      stack_name: test-github-actions-dev

  deploy-pdn:
    name: Deploy PDN
    needs: deploy-qa
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    secrets: inherit # pass all secrets
    with:
      cf_template: ${{ github.event.inputs.cf_template }}
      parameters_file: ./parameters-dev
      stack_name: test-github-actions-dev