name: Test

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: rayo-inc/terraform-aws-reference-arch/.github/workflows/deploy_cloudformation.yml@main
    #with:
    #  config-path: .github/labeler.yml