name: CD Cloudformation

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: false
        default: us-east-1
        description: AWS Region

jobs:
  deploy-dev:
    name: Deploy DEV
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    with:
      template: ./template.yaml
    secrets: inherit # pass all secrets
  
  deploy-qa:
    name: Deploy QA
    needs: deploy-dev
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    with:
      template: ./template.yaml
    secrets: inherit # pass all secrets

  deploy-pdn:
    name: Deploy PDN
    needs: deploy-qa
    uses: agustincharry/terraform-aws-test-module/.github/workflows/deploy_cloudformation.yml@main
    with:
      template: ./template.yaml
    secrets: inherit # pass all secrets